Require Import v001__late_other_mode_preserve_goal v001__late_other_mode_preserve_proof_auto v001__late_other_mode_preserve_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v001__late_other_mode_preserve_proof_auto.
  Include v001__late_other_mode_preserve_proof_manual.
End VC_Correctness.
