Require Import v001__next2_nonlate_inject_goal v001__next2_nonlate_inject_proof_auto v001__next2_nonlate_inject_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v001__next2_nonlate_inject_proof_auto.
  Include v001__next2_nonlate_inject_proof_manual.
End VC_Correctness.
