def problem_47_pre(input):
    return len(input) > 0

def problem_47_spec(input, output):
    # The Coq spec uses an existential quantification over Sorted_input.
    # It requires Sorted_input to be sorted and to have the same set of elements as input
    # (ignoring multiplicities).
    # It does not require Sorted_input to be a permutation of input.
    # Thus, Sorted_input can be any sorted list containing exactly the unique elements of input,
    # with arbitrary multiplicities.
    # We compute all possible median values that can be generated by such a Sorted_input.
    
    unique_sorted = sorted(list(set(input)))
    m = len(unique_sorted)
    n = len(input)
    halflen = n // 2
    
    possible_outputs = set()
    
    if n % 2 == 1:
        # Odd length case
        # output = nth halflen Sorted_input 0
        # Sorted_input[halflen] can be u_j if we can stretch the list such that u_j is at index halflen.
        # Since we can repeat elements, we can place u_j at any index >= j.
        # So u_j is possible if j <= halflen.
        # Also, if Sorted_input is short (length <= halflen), nth returns 0.
        # Minimal length of Sorted_input is m. So 0 is possible if m <= halflen.
        
        limit = min(m - 1, halflen)
        for j in range(limit + 1):
            possible_outputs.add(unique_sorted[j])
            
        if m <= halflen:
            possible_outputs.add(0.0)
            
    else:
        # Even length case
        # output = (nth halflen Sorted_input 0 + nth (halflen-1) Sorted_input 0) / 2
        # Let k1 = halflen, k2 = halflen - 1.
        # output = (S[k1] + S[k2]) / 2.
        # Since S is sorted, S[k2] <= S[k1].
        # Possible pairs (S[k2], S[k1]):
        # 1. (u_j, u_j): Possible if j <= k2.
        # 2. (u_j, u_{j+1}): Possible if j <= k2.
        # 3. (u_{m-1}, 0): Possible if m <= k1. (S ends at k2, so S[k2]=u_{m-1}, S[k1]=0).
        # 4. (0, 0): Possible if m <= k2.
        
        k2 = halflen - 1
        
        # Case 1: u_j
        limit = min(m - 1, k2)
        for j in range(limit + 1):
            possible_outputs.add(unique_sorted[j])
            
        # Case 2: (u_j + u_{j+1}) / 2
        limit_avg = min(m - 2, k2)
        for j in range(limit_avg + 1):
            val = (unique_sorted[j] + unique_sorted[j+1]) / 2.0
            possible_outputs.add(val)
            
        # Case 3: u_{m-1} / 2
        if m <= halflen:
            val = unique_sorted[m-1] / 2.0
            possible_outputs.add(val)
            
        # Case 4: 0.0
        if m <= k2:
            possible_outputs.add(0.0)
            
    return output in possible_outputs

def _impl(l: list):
    sorted_l = sorted(l)
    if len(l) % 2 == 1:
        return sorted_l[len(l) // 2]
    else:
        return (sorted_l[len(l) // 2 - 1] + sorted_l[len(l) // 2]) / 2

def precondition(input) -> bool:
    if not isinstance(input, tuple):
        input = tuple(input)
    return bool(problem_47_pre(*input))

def postcondition(input, output) -> bool:
    if not isinstance(input, tuple):
        input = tuple(input)
    return bool(problem_47_spec(*input, output))

def median(*args):
    _input = tuple(args)
    assert precondition(_input)
    _output = _impl(*args)
    assert postcondition(_input, _output)
    return _output
