Require Import v001__late_next2_with_inject_goal v001__late_next2_with_inject_proof_auto v001__late_next2_with_inject_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v001__late_next2_with_inject_proof_auto.
  Include v001__late_next2_with_inject_proof_manual.
End VC_Correctness.
