def factorial(n):
    """
    Calculates the factorial of n.
    Equivalent to the Coq Fixpoint factorial.
    """
    if n == 0:
        return 1
    res = 1
    for i in range(1, n + 1):
        res *= i
    return res

def sum_to_n(n):
    """
    Calculates the sum of integers from 1 to n.
    Equivalent to the Coq Fixpoint sum_to_n.
    """
    res = 0
    for i in range(1, n + 1):
        res += i
    return res

def f_spec(n, result):
    """
    Checks if the result list matches the sequence generated by applying 
    factorial to even numbers and sum_to_n to odd numbers in the range [1, n].
    Equivalent to the Coq Definition f_spec.
    """
    # Coq's (seq 1 n) generates a list [1, 2, ..., n]
    # Python's range(1, n + 1) generates the same sequence.
    expected = []
    for i in range(1, n + 1):
        # Nat.even i in Coq is equivalent to i % 2 == 0
        if i % 2 == 0:
            expected.append(factorial(i))
        else:
            expected.append(sum_to_n(i))
    
    return result == expected

def _impl(n):
    if n == 0: return []
    if n == 1: return [1]
    if n == 2: return [1, 2]
    ans = [1, 2]
    for i in range(3, n + 1):
        if i % 2 == 1:
            ans.append(ans[-2] + (i - 1) + i)
        else:
            ans.append(ans[-2] * (i - 1) * i)
    return ans

def precondition(input) -> bool:
    return True

def postcondition(input, output) -> bool:
    if not isinstance(input, tuple):
        input = tuple(input)
    return bool(f_spec(*input, output))

def f(*args):
    _input = tuple(args)
    assert precondition(_input)
    _output = _impl(*args)
    assert postcondition(_input, _output)
    return _output
