Require Import v002__switch_exact_next2_preserve_goal v002__switch_exact_next2_preserve_proof_auto v002__switch_exact_next2_preserve_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v002__switch_exact_next2_preserve_proof_auto.
  Include v002__switch_exact_next2_preserve_proof_manual.
End VC_Correctness.
