Require Import v001__switch_exact_next2_preserve_goal v001__switch_exact_next2_preserve_proof_auto v001__switch_exact_next2_preserve_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v001__switch_exact_next2_preserve_proof_auto.
  Include v001__switch_exact_next2_preserve_proof_manual.
End VC_Correctness.
