From SimpleC.EE.LLM_bench.Algorithms.longest_nondecreasing_subsequence Require Import longest_nondecreasing_subsequence_goal longest_nondecreasing_subsequence_proof_auto longest_nondecreasing_subsequence_proof_manual.

Module VC_Correctness : VC_Correct.
  Include int_array_strategy_proof.
  Include uint_array_strategy_proof.
  Include undef_uint_array_strategy_proof.
  Include array_shape_strategy_proof.
  Include longest_nondecreasing_subsequence_proof_auto.
  Include longest_nondecreasing_subsequence_proof_manual.
End VC_Correctness.
