Require Import v002__negative_switch_delay_next1_goal v002__negative_switch_delay_next1_proof_auto v002__negative_switch_delay_next1_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v002__negative_switch_delay_next1_proof_auto.
  Include v002__negative_switch_delay_next1_proof_manual.
End VC_Correctness.
