From SimpleC.EE.QCP_demos_LLM Require Import uint_array_strategy_goal uint_array_strategy_proof.

Module uint_array_Strategy_Correctness : uint_array_Strategy_Correct.
  Include uint_array_strategy_proof.
End uint_array_Strategy_Correctness.
