Require Import v001__preserve_below_both_goal v001__preserve_below_both_proof_auto v001__preserve_below_both_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v001__preserve_below_both_proof_auto.
  Include v001__preserve_below_both_proof_manual.
End VC_Correctness.
