Require Import v002__preserve_max_old_mode_goal v002__preserve_max_old_mode_proof_auto v002__preserve_max_old_mode_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v002__preserve_max_old_mode_proof_auto.
  Include v002__preserve_max_old_mode_proof_manual.
End VC_Correctness.
