Require Import v001__negative_inject_delay_goal v001__negative_inject_delay_proof_auto v001__negative_inject_delay_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v001__negative_inject_delay_proof_auto.
  Include v001__negative_inject_delay_proof_manual.
End VC_Correctness.
