def factorial(n):
    """
    Calculates the factorial of n.
    Equivalent to the Coq Fixpoint factorial.
    """
    if n == 0:
        return 1
    res = 1
    for i in range(1, n + 1):
        res *= i
    return res

def sum_to_n(n):
    """
    Calculates the sum of integers from 1 to n.
    Equivalent to the Coq Fixpoint sum_to_n.
    """
    res = 0
    for i in range(1, n + 1):
        res += i
    return res

def f_spec(n, result):
    """
    Checks if the result list matches the sequence generated by applying 
    factorial to even numbers and sum_to_n to odd numbers in the range [1, n].
    Equivalent to the Coq Definition f_spec.
    """
    # Coq's (seq 1 n) generates a list [1, 2, ..., n]
    # Python's range(1, n + 1) generates the same sequence.
    expected = []
    for i in range(1, n + 1):
        # Nat.even i in Coq is equivalent to i % 2 == 0
        if i % 2 == 0:
            expected.append(factorial(i))
        else:
            expected.append(sum_to_n(i))
    
    return result == expected
