def factorial(n):
    """
    Calculates the factorial of n.
    Equivalent to the Coq Fixpoint factorial.
    """
    if n == 0:
        return 1
    res = 1
    for i in range(1, n + 1):
        res *= i
    return res

def sum_to_n(n):
    """
    Calculates the sum of integers from 1 to n.
    Equivalent to the Coq Fixpoint sum_to_n.
    """
    res = 0
    for i in range(1, n + 1):
        res += i
    return res

def _orig_f_spec(n, output):
    """
    Checks if the output list matches the sequence generated by applying 
    factorial to even numbers and sum_to_n to odd numbers in the range [1, n].
    Equivalent to the Coq Definition f_spec.
    """
    expected = []
    for i in range(1, n + 1):
        if i % 2 == 0:
            expected.append(factorial(i))
        else:
            expected.append(sum_to_n(i))
    return output == expected

def f_spec(n, output):
    return bool(_orig_f_spec(n, output))
