From SimpleC.EE.Applications_human.LiteOS Require Import OsSortLinkGetNextExpireTime_goal OsSortLinkGetNextExpireTime_proof_auto OsSortLinkGetNextExpireTime_proof_manual.

Module VC_Correctness : VC_Correct.
  Include los_sortlink_strategy_proof.
  Include OsSortLinkGetNextExpireTime_proof_auto.
  Include OsSortLinkGetNextExpireTime_proof_manual.
End VC_Correctness.
