From SimpleC.EE.Applications_human.LiteOS Require Import OsSortLinkResponseTimeConvertFreq_goal OsSortLinkResponseTimeConvertFreq_proof_auto OsSortLinkResponseTimeConvertFreq_proof_manual.

Module VC_Correctness : VC_Correct.
  Include los_sortlink_strategy_proof.
  Include OsSortLinkResponseTimeConvertFreq_proof_auto.
  Include OsSortLinkResponseTimeConvertFreq_proof_manual.
End VC_Correctness.
