Require Import v002__late_other_mode_with_inject_goal v002__late_other_mode_with_inject_proof_auto v002__late_other_mode_with_inject_proof_manual.

Module VC_Correctness : VC_Correct.
  Include v002__late_other_mode_with_inject_proof_auto.
  Include v002__late_other_mode_with_inject_proof_manual.
End VC_Correctness.
