From SimpleC.EE.QCP_demos_tutorial Require Import branch_join_private_condition_goal branch_join_private_condition_proof_auto branch_join_private_condition_proof_manual.

Module VC_Correctness : VC_Correct.
  Include branch_join_private_condition_proof_auto.
  Include branch_join_private_condition_proof_manual.
End VC_Correctness.
